---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
gemfile:
  - .gemfiles/5.1.gemfile
  - .gemfiles/5.2.gemfile
  - .gemfiles/6.0.gemfile
before_install:
  - gem install bundler -v 1.17.2
services:
  - postgresql
  - mysql
